name: Auto-generate Vimdoc using Pandoc in CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - README.md
      - .github/**

# Set permissions of the GITHUB_TOKEN to allow modifications to files
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate docs
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: tact.vim
          version: "Vim 8+ and Neovim >= 0.10.0"
          demojify: true
          treesitter: true

      - name: Push updated doc
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto-generate vimdoc via panvimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
